### PR TITLE
FIX: npm run lint

### PR DESCRIPTION
**Pull request by allain**
Fixes to make npm run lint work again.

Specifically all calls to the method hasOwnProperty have been changed to calls to Object.prototype.hasOwnProperty.

Tests appear to all still pass.

### CODE REVIEW

**Comment by axelpale** [comment]
Oh, good job! I will look into this soon.

**Comment by allain** [comment]
For any file that uses hasOwnProperty 3 or more times I've added a hasProp function at the top.

**Comment by axelpale** [comment]
Great! Happy to merge as soon as I can.

**Comment by axelpale** [comment]
Forgive me, this took a while... better late than never :)

**Pull request merged**
